config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/about", to: "static_pages#about"

  resources :curriculum_vitaes, only: :show do
    resource :downloads, only: :show
  end

  resource :profiles, only: [:edit, :update]

  namespace :admin do
    root "static_pages#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :templates
  end

  namespace :api do
    resources :templates, only: :index
    resources :users, only: :show do
      resources :curriculum_vitaes, only: :create
    end
    resources :catalogue_forms, only: :index
  end
end

app/models/CVPdf.rb
require "render_anywhere"

class CVPdf
  include RenderAnywhere

  def initialize user
    @user = user
  end

  def to_pdf
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("#{Rails.root}/public/cv.pdf")
  end

  def filename
    "User #{user.id}.pdf"
  end

  private

  attr_reader :user

  def as_html
    render template: "downloads/show", layout: "cv_pdf", locals: {user: user}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catalogue_form.rb
class CatalogueForm < ApplicationRecord
  has_many :forms, dependent: :destroy
end

app/models/curriculum_vitae.rb
class CurriculumVitae < ApplicationRecord
  has_many :forms, dependent: :destroy
  belongs_to :user
  belongs_to :template
end

app/models/form.rb
class Form < ApplicationRecord
  has_many :sub_forms, dependent: :destroy
  belongs_to :curriculum_vitae
  belongs_to :catalogue_form
  delegate :name, to: :catalogue_form, prefix: true
end

app/models/sub_form.rb
class SubForm < ApplicationRecord
  belongs_to :form
end

app/models/template.rb
class Template < ApplicationRecord
  has_many :curriculum_vitaes, dependent: :destroy
  validates :name, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {
    admin: 0,
    member: 1
  }
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  has_many :curriculum_vitaes, dependent: :destroy

  PARAMS_ATTRIBUTES = [:first_name, :last_name, :date_of_birth, :phone_number,
    :address, :avatar, :website, :sex].freeze

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.first_name = auth.info.name
        user.password = Devise.friendly_token[0, 20]
      end
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "./admin/layouts/admin"
  before_action :last_page

  protected

  def authenticate_user!
    if user_signed_in? && current_user.admin?
      super
    else
      redirect_to admin_login_path
    end
  end

  private

  def last_page
    session[:last_page] = request.env["HTTP_REFERER"]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, except: [:index, :new, :create]
  before_action :load_roles, only: [:new, :edit]
  before_action :load_all_users, only: :index

  def index
    respond_to do |format|
      format.html{render :index}
      format.json{render json: @users}
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      render js: "window.location = '/admin/users/#{@user.id}'"
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def update
    user = params[:user]
    if user[:password].blank?
      user.delete :password
      user.delete :password_confirmation
    end
    if @user.update_attributes user_params
      render js: "window.location = '/admin/users/#{@user.id}'"
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      load_all_users
      render json: @users
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  private

  def load_all_users
    @users = User.select :id, :email, :phone_number, :role
  end

  def load_user
    @user = User.find_by! id: params[:id]
  end

  def load_roles
    @roles = User.roles
  end

  def user_params
    params.require(:user).permit :first_name, :last_name, :email, :password,
      :password_confirmation, :phone_number, :role
  end
end

app/controllers/api/templates_controller.rb
module Api
  class TemplatesController < ApplicationController
    def index
      render json: Template.all
    end
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def show
      user = User.select(:id, :first_name, :last_name, :email, :phone_number,
        :date_of_birth, :avatar, :sex, :website, :address).find_by id: params[:id]
      render json: user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth request.env["omniauth.auth"]
    sign_in_and_redirect @user
  end
end

app/controllers/curriculum_vitaes_controller.rb
class CurriculumVitaesController < ApplicationController
  def show
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  before_action :load_user, :load_data, only: :show

  def show
    respond_to do |format|
      format.pdf{send_cv_pdf}
      format.html{render_sample_html} if Rails.env.development?
    end
  end

  private

  def load_data
    @cv = CurriculumVitae.find_by! id: params[:curriculum_vitae_id]
    @template = @cv.template
    @forms = @cv.forms
  end

  def load_user
    @user = current_user
    return_404 unless @user
  end

  def create_cv_pdf
    CvPdfService.new @user
  end

  def send_cv_pdf
    send_file create_cv_pdf.to_pdf, filename: create_cv_pdf.filename,
      type: "application/pdf", disposition: "inline"
  end

  def render_sample_html
    render template: "downloads/show", layout: "cv_pdf",
      locals: {user: @user}
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes update_params
      redirect_to root_url
    else
      render :edit
    end
  end

  private

  def update_params
    params.require(:user).permit User::PARAMS_ATTRIBUTES
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
  def area_name
    controller_name == "static_pages" ? action_name : controller_name
  end

  def page_header
    headers = {
      "users" => t(".users"),
      "templates" => t(".templates"),
      "index" => t(".dashboard")
    }
    headers[area_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t ".title"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/views/admin/layouts/_header.html.erb
<%= react_component "AdminHeader", {area: area_name, current_user: current_user} %>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin", media: "all" %>
    <%= javascript_include_tag "admin" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "admin/layouts/header" %>
      <div class="page-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <h1 class="page-header">
                <%= page_header %>
              </h1>
              <%= yield :breadcrumb %>
            </div>
          </div>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/admin/layouts/users.html.erb
<% provide :page_header, t(".page_header") %>
<%= yield %>

app/views/admin/templates/_back.html.erb
<% if session[:last_page] %>
   <span class="pull-right">
    <button class="btn btn-xs btn-default" onclick="location.href='<%= session[:last_page] %>'">
      <i class="fa fa-chevron-left"></i>
      <%= t ".back" %>
    </button>
  </span>
<% end %>

app/views/admin/templates/index.html.erb
<% provide :title, t(".title") %>
<% content_for :breadcrumb do %>
  <ol class="breadcrumb">
    <li class="active">
      <i class="fa fa-files-o"></i>
      <%= t ".templates" %>
    </li>
    <span class="pull-right">
      <button class="btn btn-xs btn-default" onclick="location.href='<%= new_admin_template_path %>'">
        <i class="fa fa-plus"></i>
        <%= t ".add_new" %>
      </button>
    </span>
  </ol>
<% end %>
<%= react_component "AdminTempatesIndex", users: @templates %>

app/views/admin/templates/new.html.erb
<% provide :title, t(".title") %>
<% content_for :breadcrumb do %>
  <ol class="breadcrumb">
    <li>
      <i class="fa fa-files-o"></i>
      <%= link_to t(".templates"), admin_templates_path %>
    </li>
    <li class="active">
      <i class="fa fa-plus-square"></i>
      <%= t ".add" %>
    </li>
    <%= render "back" %>
  </ol>
<% end %>
<%= react_component "AdminNewTemplate", template: @template %>

app/views/cv_templates/_template1.html.erb
<h1>Template1</h1>

app/views/cv_templates/_template2.html.erb
<div class="container upper">
  <div class="row cv-main">
    <div class="contact-info">
      <div class="col-xs-8">
        <div class="col-xs-12 contact-name">
          <h1 class="in-pdf"><%= user.last_name %> <%= user.first_name %></h1>
        </div>
        <div class="row">
          <div class="col-xs-3 contact-title">
            <span> <%= t ".date_of_birth" %> </span>
          </div>
          <div class="contact-content col-xs-9">
            <span><%= user.date_of_birth %></span>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3 contact-title">
            <span> <%= t ".gender" %> </span>
          </div>
          <div class="contact-content col-xs-9">
            <span><%= user.sex %></span>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3 contact-title">
            <span> <%= t ".phone" %> </span>
          </div>
          <div class="contact-content col-xs-9">
            <span><%= user.phone_number %></span>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3 contact-title">
            <span> <%= t ".email" %> </span>
          </div>
          <div class="contact-content col-xs-9">
            <span><%= user.email %></span>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3 contact-title">
            <span> <%= t ".address" %> </span>
          </div>
          <div class="contact-content col-xs-9">
            <span><%= user.address %></span>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3 contact-title">
            <span> <%= t ".website" %> </span>
          </div>
          <div class="contact-content col-xs-9">
            <span><%= user.website %></span>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <img class="user-image" src="<%= root_url %>/thanh.jpg" alt="avatar"
          type="image" height="170px"/>
      </div>
    </div>
    <div class="form-info">
      <% forms.each do |form| %>
        <div class="form-info col-xs-12">
          <div class="col-xs-12 form-title">
            <div class="input-text">
              <%= form.catalogue_form_name %>
            </div>
            <hr/>
          </div>
          <% form.sub_forms.each do |sub_form| %>
            <div class="col-xs-12">
              <div class="row subform">
                <% if sub_form.time %>
                <div class="col-xs-3">
                  <%= sub_form.time %>
                </div>
                <% end %>
                <div class="col-xs-<%= sub_form.time ? 9 : 12 %> title-content">
                  <div class="input-text">
                    <div class="title">
                      <%= sub_form.title %>
                    </div>
                  </div>
                  <div class="input-text">
                    <%= sub_form.content %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<%= react_component "Footer" %>

app/views/layouts/_header.html.erb
<%= react_component "Header", user_signed_in: user_signed_in?,
  change_password_link: edit_user_registration_path,
  logout_link: destroy_user_session_path,
  signup_link: new_user_registration_path,
  login_link: new_user_session_path,
  edit_profile_link: edit_profiles_path
%>

app/views/layouts/_notice.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class = "container">
      <%= render "layouts/notice" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/cv_pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t ".title" %></title>
  <style>
    <%= Rails.application.assets.find_asset("application.scss").to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>