config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/about", to: "static_pages#about"

  resources :curriculum_vitaes, only: :show do
    resource :downloads, only: :show
  end

  resource :profiles, only: [:edit, :update]

  namespace :admin do
    root "static_pages#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :templates
  end

  namespace :api do
    resources :templates, only: :index
    resources :users, only: :show do
      resources :curriculum_vitaes, only: :create
    end
    resources :catalogue_forms, only: :index
  end
end

app/models/CVPdf.rb
require "render_anywhere"

class CVPdf
  include RenderAnywhere

  def initialize user
    @user = user
  end

  def to_pdf
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("#{Rails.root}/public/cv.pdf")
  end

  def filename
    "User #{user.id}.pdf"
  end

  private

  attr_reader :user

  def as_html
    render template: "downloads/show", layout: "cv_pdf", locals: {user: user}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catalogue_form.rb
class CatalogueForm < ApplicationRecord
  has_many :forms, dependent: :destroy
end

app/models/curriculum_vitae.rb
class CurriculumVitae < ApplicationRecord
  has_many :forms, dependent: :destroy
  belongs_to :user
  belongs_to :template
end

app/models/form.rb
class Form < ApplicationRecord
  has_many :sub_forms, dependent: :destroy
  belongs_to :curriculum_vitae
  belongs_to :catalogue_form
  delegate :name, to: :catalogue_form, prefix: true
end

app/models/sub_form.rb
class SubForm < ApplicationRecord
  belongs_to :form
end

app/models/template.rb
class Template < ApplicationRecord
  has_many :curriculum_vitaes, dependent: :destroy
  validates :name, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {
    admin: 0,
    member: 1
  }
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  has_many :curriculum_vitaes, dependent: :destroy

  PARAMS_ATTRIBUTES = [:first_name, :last_name, :date_of_birth, :phone_number,
    :address, :avatar, :website, :sex].freeze

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.first_name = auth.info.name
        user.password = Devise.friendly_token[0, 20]
      end
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "./admin/layouts/admin"
  before_action :last_page

  protected

  def authenticate_user!
    if user_signed_in? && current_user.admin?
      super
    else
      redirect_to admin_login_path
    end
  end

  private

  def last_page
    session[:last_page] = request.env["HTTP_REFERER"]
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController
  layout false
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
  end

  def create
    user_param = params[:user]
    @user = User.find_by email: user_param[:email]
    if @user && @user.valid_password?(user_param[:password])
      if @user.admin?
        sign_in @user
        render js: "window.location = '/admin'"
      else
        render json: {message: "Need admin account"}
      end
    else
      render json: {message: "Incorrect email or password"}
    end
  end

  def destroy
    sign_out
    render js: "window.location = '/admin/login'"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, except: [:index, :new, :create]
  before_action :load_roles, only: [:new, :edit]
  before_action :load_all_users, only: :index

  def index
    respond_to do |format|
      format.html{render :index}
      format.json{render json: @users}
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      render js: "window.location = '/admin/users/#{@user.id}'"
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def update
    user = params[:user]
    if user[:password].blank?
      user.delete :password
      user.delete :password_confirmation
    end
    if @user.update_attributes user_params
      render js: "window.location = '/admin/users/#{@user.id}'"
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      load_all_users
      render json: @users
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  private

  def load_all_users
    @users = User.select :id, :email, :phone_number, :role
  end

  def load_user
    @user = User.find_by! id: params[:id]
  end

  def load_roles
    @roles = User.roles
  end

  def user_params
    params.require(:user).permit :first_name, :last_name, :email, :password,
      :password_confirmation, :phone_number, :role
  end
end

app/controllers/api/templates_controller.rb
module Api
  class TemplatesController < ApplicationController
    def index
      render json: Template.all
    end
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def show
      user = User.select(:id, :first_name, :last_name, :email, :phone_number,
        :date_of_birth, :avatar, :sex, :website, :address).find_by id: params[:id]
      render json: user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth request.env["omniauth.auth"]
    sign_in_and_redirect @user
  end
end

app/controllers/curriculum_vitaes_controller.rb
class CurriculumVitaesController < ApplicationController
  def show
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  before_action :load_user, :load_data, only: :show

  def show
    respond_to do |format|
      format.pdf{send_cv_pdf}
      format.html{render_sample_html} if Rails.env.development?
    end
  end

  private

  def load_data
    @cv = CurriculumVitae.find_by! id: params[:curriculum_vitae_id]
    @template = @cv.template
    @forms = @cv.forms
  end

  def load_user
    @user = current_user
    return_404 unless @user
  end

  def create_cv_pdf
    CvPdfService.new @user
  end

  def send_cv_pdf
    send_file create_cv_pdf.to_pdf, filename: create_cv_pdf.filename,
      type: "application/pdf", disposition: "inline"
  end

  def render_sample_html
    render template: "downloads/show", layout: "cv_pdf",
      locals: {user: @user}
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes update_params
      redirect_to root_url
    else
      render :edit
    end
  end

  private

  def update_params
    params.require(:user).permit User::PARAMS_ATTRIBUTES
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
  def area_name
    controller_name == "static_pages" ? action_name : controller_name
  end

  def page_header
    headers = {
      "users" => t(".users"),
      "templates" => t(".templates"),
      "index" => t(".dashboard")
    }
    headers[area_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t ".title"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/views/downloads/show.html.erb
<%= render partial: "cv_templates/#{@template.content}", locals: {user: @user, forms: @forms} %>

app/views/profiles/edit.html.erb
<div class="form-horizontal">
  <%= form_for @user, url: profiles_path do |f| %>
    <%= field_set_tag t(".title") do %>
      <div class="form-group">
        <%= f.label :email, class: "control-label col-md-2" %>
        <div class="controls col-md-10">
          <%= f.email_field :email, class: "form-control", disabled: true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :first_name, class: "control-label col-md-2" %>
        <div class="controls col-md-4">
          <%= f.text_field :first_name, class: "form-control", required: true %>
        </div>
        <%= f.label :last_name, class: "control-label col-md-2" %>
        <div class="controls col-md-4">
          <%= f.text_field :last_name, class: "form-control", required: true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :sex, class: "control-label col-md-2" %>
        <div class="controls col-md-2">
          <%= f.text_field :sex, class: "form-control", required: true %>
        </div>
        <%= f.label :date_of_birth, class: "control-label col-md-2" %>
        <div class="controls col-md-2">
          <%= f.date_field :date_of_birth, class: "form-control", required: true %>
        </div>
        <%= f.label :phone_number, class: "control-label col-md-2" %>
        <div class="controls col-md-2">
          <%= f.telephone_field :phone_number, class: "form-control", required: true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :website, class: "control-label col-md-2" %>
        <div class="controls col-md-10">
          <%= f.text_field :website, class: "form-control", required: true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :address, class: "control-label col-md-2" %>
        <div class="controls col-md-10">
          <%= f.text_area :address, class: "form-control", required: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="controls col-md-10 col-md-offset-2">
          <%= f.submit t(".submit"), class: "btn btn-success" %>
          <%= link_to t(".back"), :back, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>