config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/about", to: "static_pages#about"

  resources :curriculum_vitaes, only: :show do
    resource :downloads, only: :show
  end

  resource :profiles, only: [:edit, :update]

  namespace :admin do
    root "static_pages#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :templates
  end

  namespace :api do
    resources :templates, only: :index
    resources :users, only: :show do
      resources :curriculum_vitaes, only: :create
    end
    resources :catalogue_forms, only: :index
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {
    admin: 0,
    member: 1
  }
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  has_many :curriculum_vitaes, dependent: :destroy

  PARAMS_ATTRIBUTES = [:first_name, :last_name, :date_of_birth, :phone_number,
    :address, :avatar, :website, :sex].freeze

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.first_name = auth.info.name
        user.password = Devise.friendly_token[0, 20]
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, except: [:index, :new, :create]
  before_action :load_roles, only: [:new, :edit]
  before_action :load_all_users, only: :index

  def index
    respond_to do |format|
      format.html{render :index}
      format.json{render json: @users}
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      render js: "window.location = '/admin/users/#{@user.id}'"
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def update
    user = params[:user]
    if user[:password].blank?
      user.delete :password
      user.delete :password_confirmation
    end
    if @user.update_attributes user_params
      render js: "window.location = '/admin/users/#{@user.id}'"
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      load_all_users
      render json: @users
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  private

  def load_all_users
    @users = User.select :id, :email, :phone_number, :role
  end

  def load_user
    @user = User.find_by! id: params[:id]
  end

  def load_roles
    @roles = User.roles
  end

  def user_params
    params.require(:user).permit :first_name, :last_name, :email, :password,
      :password_confirmation, :phone_number, :role
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def show
      user = User.select(:id, :first_name, :last_name, :email, :phone_number,
        :date_of_birth, :avatar, :sex, :website, :address).find_by id: params[:id]
      render json: user
    end
  end
end

app/views/users/shared/_links.html.erb
<%- if controller_name != t(".sessions") %>
  <%= link_to t(".login"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != t(".registrations") %>
  <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != t(".passwords") &&
  controller_name != t(".registrations") %>

  <%= link_to t(".forgot_pwd"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != t(".confirmations") %>
  <%= link_to t(".dont_receive_confirm"),
    new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? &&
  resource_class.unlock_strategy_enabled?(:email) &&
  controller_name != t(".unlocks") %>

  <%= link_to t(".dont_receive_unlock"), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t(".authenticated", OmniAuth::Utils.camelize(provider)),
      omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>