config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/about", to: "static_pages#about"

  resources :curriculum_vitaes, only: :show do
    resource :downloads, only: :show
  end

  resource :profiles, only: [:edit, :update]

  namespace :admin do
    root "static_pages#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :templates
  end

  namespace :api do
    resources :templates, only: :index
    resources :users, only: :show do
      resources :curriculum_vitaes, only: :create
    end
    resources :catalogue_forms, only: :index
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {
    admin: 0,
    member: 1
  }
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  has_many :curriculum_vitaes, dependent: :destroy

  PARAMS_ATTRIBUTES = [:first_name, :last_name, :date_of_birth, :phone_number,
    :address, :avatar, :website, :sex].freeze

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.first_name = auth.info.name
        user.password = Devise.friendly_token[0, 20]
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, except: [:index, :new, :create]
  before_action :load_roles, only: [:new, :edit]
  before_action :load_all_users, only: :index

  def index
    respond_to do |format|
      format.html{render :index}
      format.json{render json: @users}
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      render js: "window.location = '/admin/users/#{@user.id}'"
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def update
    user = params[:user]
    if user[:password].blank?
      user.delete :password
      user.delete :password_confirmation
    end
    if @user.update_attributes user_params
      render js: "window.location = '/admin/users/#{@user.id}'"
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      load_all_users
      render json: @users
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  private

  def load_all_users
    @users = User.select :id, :email, :phone_number, :role
  end

  def load_user
    @user = User.find_by! id: params[:id]
  end

  def load_roles
    @roles = User.roles
  end

  def user_params
    params.require(:user).permit :first_name, :last_name, :email, :password,
      :password_confirmation, :phone_number, :role
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def show
      user = User.select(:id, :first_name, :last_name, :email, :phone_number,
        :date_of_birth, :avatar, :sex, :website, :address).find_by id: params[:id]
      render json: user
    end
  end
end

app/views/admin/users/edit.html.erb
<% provide :title, t(".title") %>
<% content_for :breadcrumb do %>
  <ol class="breadcrumb">
    <li>
      <i class="fa fa-users"></i>
      <%= link_to t(".users"), admin_users_path %>
    </li>
    <li class="active">
      <i class="fa fa-pencil-square"></i>
      Edit
    </li>
    <%= render "back" %>
  </ol>
<% end %>
<%= react_component "AdminEditUser", user: @user, roles: @roles %>

app/views/admin/users/index.html.erb
<% provide :title, t(".title") %>
<% content_for :breadcrumb do %>
  <ol class="breadcrumb">
    <li class="active">
      <i class="fa fa-users"></i>
      <%= t ".users" %>
    </li>
    <span class="pull-right">
      <button class="btn btn-xs btn-default" onclick="location.href='<%= new_admin_user_path %>'">
        <i class="fa fa-plus"></i>
        <%= t ".add_new" %>
      </button>
    </span>
  </ol>
<% end %>
<%= react_component "AdminUsersIndex", users: @users %>

app/views/admin/users/new.html.erb
<% provide :title, t(".title") %>
<% content_for :breadcrumb do %>
  <ol class="breadcrumb">
    <li>
      <i class="fa fa-users"></i>
      <%= link_to t(".user"), admin_users_path %>
    </li>
    <li class="active">
      <i class="fa fa-plus-square"></i>
      <%= t ".add" %>
    </li>
    <%= render "back" %>
  </ol>
<% end %>
<%= react_component "AdminNewUser", roles: @roles %>

app/views/admin/users/show.html.erb
<% provide :title, t(".title") %>
<% content_for :breadcrumb do %>
  <ol class="breadcrumb">
    <li>
      <i class="fa fa-users"></i>
      <%= link_to t(".users"), admin_users_path %>
    </li>
    <li class="active">
      <i class="fa fa-info-circle"></i>
      Details
    </li>
    <%= render "back" %>
  </ol>
<% end %>
<%= react_component "AdminShowUser", user: @user %>